import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import {AuthProvider} from "@/context/AuthProvider";
import {Toaster} from "@/components/ui/sonner";
import {ThemeProvider} from "@/components/ThemeProvider";





export const metadata: Metadata = {
  title: "AI-TUBE",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets: ['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>

      <html lang="en">
        <body
          className={outfit.className}
        >
        <ThemeProvider attribute='class'
                       enableSystem={true}
                       disableTransitionOnChange={true}
                       defaultTheme='system'>


          <Provider>
            {children}
          <Toaster/>
          </Provider>
        </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
